version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 10
    commands:
      - npm install -g jest
      - npm install -g gatsby

  build:
    commands:
      - npm run test:ci

cache:
  paths:
    - './node_modules/**/*'
